name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Pull submodules
      run: git submodule update --init --recursive

    - name: Build the Docker image
      run: docker build . --tag ghcr.io/uchile-instituto/moodle-instituto:${GITHUB_SHA}

    - name: Push to Github Container Registry
      run: |
          echo "${CR_PAT}" | docker login ghcr.io -u inbotcl --password-stdin
          docker push ghcr.io/uchile-instituto/moodle-instituto:${GITHUB_SHA}
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
